
from decouple import config

EMAIL_USER = config('EMAIL_USER')
NAME_USER = config('NAME_USER')
SURNAME_USER = config('SURNAME_USER')
PASSWORD_USER = config('PASSWORD_USER')
ADDRESS_USER = config('ADDRESS_USER')
CITY_USER = config('CITY_USER')
STATE_USER = config('STATE_USER')
POST_CODE_USER = config('POST_CODE_USER')
NUMBER_USER = config('NUMBER_USER')
ALIAS_USER = config('ALIAS_USER')



