
from decouple import config


PURCHASE_UNITARY_LIMIT = config('PURCHASE_UNITARY_LIMIT', cast=float)
MAX_COLUMS = config('MAX_COLUMS', cast=int)

CARD = config('CARD',cast=int)
CHEQUE = config('CHEQUE',cast=int)
URL = config('URL')
SEARCH = config('SEARCH')
LOGIN_BUTTON = config('LOGIN_BUTTON')
EMAIL_CREATE = config('EMAIL_CREATE')
EMAIL_CREATE_BUTTON = config('EMAIL_CREATE_BUTTON')
NAME_INPUT = config('NAME_INPUT')
APELLIDO_INPUT = config('APELLIDO_INPUT')
PASSWORD_INPUT = config('PASSWORD_INPUT')
ADDRESS_INPUT = config('ADDRESS_INPUT')
CITY_INPUT = config('CITY_INPUT')
SELECT_STATE_INPUT = config('SELECT_STATE_INPUT')
SELECT_OPTIONS = config('SELECT_OPTIONS')
POST_CODE_INPUT = config('POST_CODE_INPUT')
NUMBER_INPUT = config('NUMBER_INPUT')
ALIAS_INPUT = config('ALIAS_INPUT')
SUBMIT_CREATE_ACCOUNT = config('SUBMIT_CREATE_ACCOUNT')


EMAIL_INPUT = config('EMAIL_INPUT')

PASSWORD_ACCOUNT_INPUT = config('PASSWORD_ACCOUNT_INPUT')
SUBMIT_LOGIN = config('SUBMIT_LOGIN')

SEARCH_BUTTON = config('SEARCH_BUTTON')

SEARCH_PRODUCT_LISTING = config('SEARCH_PRODUCT_LISTING')
NOT_RESULT= config('NOT_RESULT')
SEARCH_PRODUCTS_RESULTS = config('SEARCH_PRODUCTS_RESULTS')

MODEL_PRODUCT = config('MODEL_PRODUCT')

PRICE_PRODUCT = config('PRICE_PRODUCT')

GO_BACK_RESULTS = config('GO_BACK_RESULTS')

ICON_PLUS = config('ICON_PLUS')

ADD_TO_CART = config('ADD_TO_CART')
TAKE_QUANTITY = config('TAKE_QUANTITY')
EXIT_EMERGETN_WINDOW = config('EXIT_EMERGETN_WINDOW')

GO_CART = config('GO_CART')

NEXT_STEP = config('NEXT_STEP')

NEXT_STEP_II = config('NEXT_STEP_II')

ACCEPT_TERMS_AND_CONDITIONS = config('ACCEPT_TERMS_AND_CONDITIONS')

NEXT_STEP_III = config('NEXT_STEP_III')

CARD_SELECTION_BUTTON = config('CARD_SELECTION_BUTTON')

CONFIRM_ORDER_WITH_CARD = config('CONFIRM_ORDER_WITH_CARD')

CONFIRM_ORDER_WITH_CHECK = config('CONFIRM_ORDER_WITH_CHECK')

CHEQUE_SELECTION_BUTTON = config('CHEQUE_SELECTION_BUTTON')

CONFIRM_ORDER_WITH_CHECK = config('CONFIRM_ORDER_WITH_CHECK')

GO_TO_PURCHARSE_ORDERS = config('GO_TO_PURCHARSE_ORDERS')

PURCHARSE_ORDER = config('PURCHARSE_ORDER')
TOTAL_SHIPPING= config('TOTAL_SHIPPING')

EMAIL_USER = config('EMAIL_USER')
NAME_USER = config('NAME_USER')
SURNAME_USER = config('SURNAME_USER')
PASSWORD_USER = config('PASSWORD_USER')
ADDRESS_USER = config('ADDRESS_USER')
CITY_USER = config('CITY_USER')
STATE_USER = config('STATE_USER')
POST_CODE_USER = config('POST_CODE_USER')
NUMBER_USER = config('NUMBER_USER')
ALIAS_USER = config('ALIAS_USER')


ARCHIVO_STORE = config('ARCHIVO_STORE')

NAME_ELEMENT = config('NAME_ELEMENT')
COLOR = config('COLOR')
SEPARATE_COLOR = config('SEPARATE_COLOR')
MODEL = config('MODEL')
UNIT_PRICE = config('UNIT_PRICE')
AMOUNT = config('AMOUNT')
PURCHARSE_GENERATED_ORDER = config('PURCHARSE_GENERATED_ORDER')

ORDERED =config('ORDERED') 
TOTALS =config('TOTALS') 

TOTAL_C_SHIPPING =config('TOTAL_C_SHIPPING') 
TOTAL_S_SHIPPING =config('TOTAL_S_SHIPPING') 
COST_SHIPPING =config('COST_SHIPPING') 
DATE_PURCHASE =config('DATE_PURCHASE') 



##################################################
CALYX_LOG = config('CALYX_LOG')
OPEN_ICON = config('OPEN_ICON')
MAIN_ID = config('MAIN_ID')
NUM_FIELDS = config('NUM_FIELDS', cast=int)
ADD_ITEM = config('ADD_ITEM')
PREPARE_TO_WRTIE = config('PREPARE_TO_WRTIE')
INTER_OF_CLICK = config('INTER_OF_CLICK', cast=float)
INTER_OF_WRITE = config('INTER_OF_WRITE', cast=float)
PAGE_DOWN = config('PAGE_DOWN')
RIGHT = config('RIGHT')
SAVE = config('SAVE')
ENTER = config('ENTER')
APP_OPTION = config('APP_OPTION')
EXIT = config('EXIT')
MAX = config('MAX', cast=int)


BILLS_FILE =  config('BILLS_FILE')
BILLS_COLUMNS = config('BILLS_COLUMNS', cast=int)
NAME_MAIN_ID = config('NAME_MAIN_ID')

NUMBER_KEY= config('NUMBER_KEY')
IDENTITY = config('IDENTITY')
BUYER = config('BUYER')
UNIT_AMOUNT = config('UNIT_AMOUNT')
PARTIAL_AMOUNT = config('PARTIAL_AMOUNT')


####################################################


MESSAGE_ELEMENT_NOT_CLICKED = config('MESSAGE_ELEMENT_NOT_CLICKED')
MESSAGE_ELEMENT_NOT_SENT_KEYS = config('MESSAGE_ELEMENT_NOT_SENT_KEYS')
MESSAGE_ELEMENT_NOT_FOUND = config('MESSAGE_ELEMENT_NOT_FOUND')
MESSAGE_INPUT_SEARCH_NOT_SET = config('MESSAGE_INPUT_SEARCH_NOT_SET')
MESSAGE_OPTION_NOT_SELECTED = config('MESSAGE_OPTION_NOT_SELECTED')
MESSAGE_STORE_PAGE_NOT_OPEN = config('MESSAGE_STORE_PAGE_NOT_OPEN')
MESSAGE_REGISTER_NOT_DONE = config('MESSAGE_REGISTER_NOT_DONE')
MESSAGE_LOGIN_NOT_DONE = config('MESSAGE_LOGIN_NOT_DONE')
MESSAGE_PRODUCT_NOT_SEARCHED = config('MESSAGE_PRODUCT_NOT_SEARCHED')
MESSAGE_MODEL_NOT_SEARCHED = config('MESSAGE_MODEL_NOT_SEARCHED')
MESSAGE_NOT_ADDED_TO_CART = config('MESSAGE_NOT_ADDED_TO_CART')
MESSAGE_PURCHASE_NOT_DONE = config('MESSAGE_PURCHASE_NOT_DONE')
MESSAGE_UNEXPECTED_ERROR = config('MESSAGE_UNEXPECTED_ERROR')
MESSAGE_CANNOT_ORDER_PRODUCT = config('MESSAGE_CANNOT_ORDER_PRODUCT')

CANNOT_LOCATE_SCREEN = config('CANNOT_LOCATE_SCREEN')

YES = config('YES')
NO = config('NO')

SYSTEMLOG = config('SYSTEMLOG')

